---

- name: Create Pyats Testbed From Ansible Inventory
  hosts: "{{ _devices }}"
  gather_facts: no
  vars:
    _devices:
      - ios 

  tasks:
  
  - name: Flatten Group Name To Device List.
    set_fact:
      _testbed: '{{ _devices | map("extract", groups) | flatten | list }}'

  - name: Template Ansible Inventory Devices To Testbed.yml
    template:
      src: testbed.j2
      dest: testbed.yml

  
